import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { DM_Sans, Kalam } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { PMCTheme } from "./themes";
import { RenameModalProvider } from "@/context/RenameModalContext";
import { SettingsModalProvider } from "@/context/SettingsModalContext";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  display: "swap",
});

const kalam = Kalam({
  variable: "--font-kalam",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ConfigProvider theme={PMCTheme}>
      <html lang="en">
        <body className={`${dmSans.variable} ${kalam.variable} antialiased`}>
          <AntdRegistry>
            {/* Make RenameModalProvider wrap SettingsModalProvider */}
            <RenameModalProvider>
              <SettingsModalProvider>{children}</SettingsModalProvider>
            </RenameModalProvider>
          </AntdRegistry>
        </body>
      </html>
    </ConfigProvider>
  );
}
